### ISSUE TITLE
Broken with latest version of Nuxt

### ISSUE THREAD

**Issue by Tahul** [Tahul/pinceau#93] opened 2023-05-04 08:52 UTC
![image](https://user-images.githubusercontent.com/1385263/236156379-78c6ba32-4823-4c35-b91e-8589d0a9e552.png)

Reported by @Atinux ;

Can be worked around using `experimental.inlineSSRStyles: false` in the `nuxt.config` file while it gets fixed.

**Comment by Tahul** [comment] 2023-05-04 10:17
https://stackblitz.com/edit/nuxt-starter-bst9ma?file=package.json,nuxt.config.ts,app.vue

First trial at making a reproduction, couldn't manage to get it outside of Docus context.

**Comment by Tahul** [comment] 2023-05-04 10:30
https://stackblitz.com/edit/nuxt-starter-sgyeu1

Second reproduction, using a layer loaded from `node_modules`.

**Comment by danielroe** [comment] 2023-05-04 12:02
Thanks for the reproductions. Having bisected this, the initial regression was caused by https://github.com/nuxt/nuxt/pull/20547. I suspect we can solve in same PR with https://github.com/nuxt/nuxt/issues/20650.

cc: @antfu

**Comment by antfu** [comment] 2023-05-04 12:10
> [stackblitz.com/edit/nuxt-starter-sgyeu1](https://stackblitz.com/edit/nuxt-starter-sgyeu1)
> 
> Second reproduction, using a layer loaded from `node_modules`.

I tried this, and it seems that both `npm run build` and `npm run generate` are working fine. What's the step to reproduce it? If you have it locally, can you tried with the edge release? The regression of https://github.com/nuxt/nuxt/pull/20547 should already be fixed by https://github.com/nuxt/nuxt/pull/20591.

**Comment by danielroe** [comment] 2023-05-04 12:33
Apologies, the reproduction is https://github.com/Tahul/pinceau/tree/issue/93.

**Closed** 2023-05-04 16:19 UTC
